### ISSUE TITLE
Customer.io sending needs authentication

### ISSUE THREAD

**Issue by hieggelke** [rentapplication/emails#4]
In each workspace where we want to send emails in CIO, we need to authenticate so the message doesn't show the  "via customer.io" portion

https://fly.customer.io/env/11583/actions/email/deliverability
and
https://fly.customer.io/env/74632/actions/email/deliverability  (both domain names)

It looks like GoDaddy is the registrar for rentapplication.net.

<img width="607" alt="screen shot 2019-03-07 at 9 52 42 am" src="https://user-images.githubusercontent.com/34511/53969754-f4690d00-40be-11e9-9311-2acc862c9dee.png">

**Comment by hieggelke** [comment]
@shchoi22 

apparently our DNS settings for rentapplication.net are in AWS and i'm hoping you have the access to update -> can you add the values specified here:  

- https://fly.customer.io/env/11583/actions/email/deliverability/1   **(TXT and CNAME settings)**

This will sign CIO's ability to send as rentapp domain.

**Comment by shchoi22** [comment]
@hieggelke Updated. Though I'm not sure if I have to do something else to enable HTTPS as it doesn't seem enabled when I add the records.

As far as tenantreport.com domain, I don't have access to it so can't update it for you. I believe @ezl has access to them.

**Comment by hieggelke** [comment]
re: tenantreport i don't think we use it for anything anyways. that workspace doesn't seem active.

re: https, it may not be needed unless we move some transactional messages in which should probably all be https (https://customer.io/docs/https-link-verification#setting-up-https-link-tracking-with-amazon-cloudfront )

**Comment by shchoi22** [comment]
@hieggelke Is it safe to close this issue then?
