### ISSUE TITLE
[ID Verification] Update copy in Postmark template 

### ISSUE THREAD

**Issue by RRusso77** [rentapplication/emails#5]
# Update subject line

Action Required: Verify your identity for application to {property_address_Value} 

# Updated copy

Your submitted application for the property at property_address_Value requires an additional verification step. This should only take 2 minutes to complete. Please have a valid government photo ID ready and click below when you are ready to begin. 

**This link is valid for 48 hours, and can only be clicked once.** 

{LINK}

The Rent Application Verifications Team

(855) 949-9988
verification@rentapplication.net

Application Id: application_id_Value

# Additional request
There is a link to support at the bottom of the email- likely just part of the template. Can this be removed OR updated to the verification@rentapplication.net contact info (including phone number)? Having 2 different paths for help is confusing. 

<img width="732" alt="Postmark | Rent Application   Edit Template 2022-12-27 09-23-13" src="https://user-images.githubusercontent.com/12900899/209687172-08f6d49c-c3bf-4e4a-b8dd-08bcf7b0b917.png">

**Comment by shchoi22** [comment]
@RRusso77 
Updated on Postmark. Please use https://github.com/rentapplication/django-rentapplication repo for email updates going forward.
