### ISSUE TITLE
[Link to Apply] Fix icon that is not rendering in sent emails

### ISSUE THREAD

**Issue by RRusso77** [rentapplication/emails#7]
# Issue
When a landlord user clicks the Send button to generate an email welcoming an applicant to apply to their form, the email sent has an icon that does not display properly. 

User reported directly to Robin (eric.margolis@realtor.com) sending this screen shot: 
![IMG_20240521_172950](https://github.com/rentapplication/emails/assets/12900899/1cc11115-4b7e-4267-b3e2-63a58b986cf0)

Confirmed in my own email: 
<img width="988" alt="Screenshot 2024-05-22 at 8 30 48 AM" src="https://github.com/rentapplication/emails/assets/12900899/349ccf32-2bf5-4188-98be-1d81e2695eda">

In Postmark, looks fine: 
https://account.postmarkapp.com/servers/3156175/streams/outbound/messages/37e7352d-a8ff-451f-8371-0b9b61455333
https://account.postmarkapp.com/servers/3156175/streams/outbound/messages/2f49fe12-be29-455a-8d7a-f3dbfa4cfdfa

# Ideal behavior
Design elements should display properly 

# Urgency
Not urgent

**Comment by shchoi22** [comment]
@RRusso77 Do not use this repo. This repo is not used for anything.

**Comment by shchoi22** [comment]
Closing as I cannot replicate this.
![Screenshot 2024-05-23 at 4 01 07 AM](https://github.com/rentapplication/emails/assets/4170321/8406e7ae-f830-4da5-a728-df1df4a500c1)
